# Type stubs for tomlkit.exceptions

class TOMLKitError(Exception): ...
class ParseError(TOMLKitError): ...
class MixedArrayTypesError(ParseError): ...
class InvalidNumberError(ParseError): ...
class InvalidDateTimeError(ParseError): ...
class InvalidDateError(ParseError): ...
class InvalidTimeError(ParseError): ...
class InvalidNumberOrDateError(ParseError): ...
class InvalidUnicodeValueError(ParseError): ...
class UnexpectedCharError(ParseError): ...
class EmptyKeyError(ParseError): ...
class EmptyTableNameError(ParseError): ...
class InvalidCharInStringError(ParseError): ...
class UnexpectedEofError(ParseError): ...
class InternalParserError(ParseError): ...
class NonExistentKey(TOMLKitError, KeyError): ...
class KeyAlreadyPresent(TOMLKitError): ...
class InvalidControlChar(ParseError): ...
